## Importing the packages

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!ls

sample_data

In [ ]:
from scipy.io import arff

In [ ]:
data_0 = arff.loadarff('sample_data/1year.arff')

In [ ]:
data_5 = arff.loadarff('sample_data/5year.arff')
data_4 = arff.loadarff('sample_data/4year.arff')
data_3 = arff.loadarff('sample_data/3year.arff')
data_2 = arff.loadarff('sample_data/2year.arff')
data_1 = arff.loadarff('sample_data/1year.arff')

In [ ]:
df_5 = pd.DataFrame(data_5[0])
df_4 = pd.DataFrame(data_4[0])
df_3 = pd.DataFrame(data_3[0])
df_2 = pd.DataFrame(data_2[0])
df_1 = pd.DataFrame(data_1[0])

## Data decription and appends

In [ ]:
df = pd.concat([df_5, df_4, df_3, df_2, df_1], 0)

In [ ]:
df.head()

      Attr1    Attr2    Attr3   Attr4  ...   Attr62  Attr63  Attr64  class
0  0.088238  0.55472  0.01134  1.0205  ...  142.760  2.5568  3.2597   b'0'
1 -0.006202  0.48465  0.23298  1.5998  ...  111.140  3.2841  3.3700   b'0'
2  0.130240  0.22142  0.57751  3.6082  ...   71.531  5.1027  5.6188   b'0'
3 -0.089951  0.88700  0.26927  1.5222  ...  147.560  2.4735  5.9299   b'0'
4  0.048179  0.55041  0.10765  1.2437  ...  106.430  3.4294  3.3622   b'0'

[5 rows x 65 columns]

In [ ]:
df['class'] = df['class'].astype('float')

In [ ]:
df.describe().T

          count         mean            std  ...       50%        75%           max
Attr1   43397.0     0.035160       2.994109  ...   0.04966    0.12958  9.428000e+01
Attr2   43397.0     0.590212       5.842748  ...   0.47190    0.68832  4.809600e+02
Attr3   43397.0     0.114431       5.439429  ...   0.19661    0.40339  2.833600e+01
Attr4   43271.0     6.314702     295.434425  ...   1.56980    2.78745  5.343300e+04
Attr5   43316.0  -385.346602   61243.025874  ...  -1.03450   50.63425  1.250100e+06
...         ...          ...            ...  ...       ...        ...           ...
Attr61  43303.0    17.033202     553.049406  ...   6.63630   10.39450  1.080000e+05
Attr62  43278.0  1502.327833  139266.699576  ...  71.32600  117.22000  2.501600e+07
Attr63  43271.0     9.343074     124.177354  ...   5.08760    8.59885  2.345400e+04
Attr64  42593.0    72.788592    2369.339482  ...   4.28250    9.77620  2.947700e+05
class   43405.0     0.048174       0.214137  ...   0.00000    0.00000  1.000000e+00

[65 rows x 8 columns]

## Correlations

In [ ]:
df.corr()

           Attr1     Attr2     Attr3  ...    Attr63    Attr64     class
Attr1   1.000000 -0.104146  0.058037  ...  0.008387 -0.069029 -0.026649
Attr2  -0.104146  1.000000 -0.926983  ... -0.003339 -0.015649  0.035236
Attr3   0.058037 -0.926983  1.000000  ...  0.004044 -0.000909 -0.035128
Attr4   0.000855 -0.001589  0.002335  ...  0.039447  0.000122 -0.001652
Attr5   0.002742 -0.036344  0.038900  ...  0.000690  0.000198 -0.001327
...          ...       ...       ...  ...       ...       ...       ...
Attr61  0.000582 -0.001191 -0.000139  ...  0.109143  0.147088 -0.000696
Attr62  0.000325  0.046871 -0.050162  ... -0.000793 -0.000272 -0.000113
Attr63  0.008387 -0.003339  0.004044  ...  1.000000  0.277732 -0.000854
Attr64 -0.069029 -0.015649 -0.000909  ...  0.277732  1.000000  0.003337
class  -0.026649  0.035236 -0.035128  ... -0.000854  0.003337  1.000000

[65 rows x 65 columns]

Drop on correlation

In [ ]:
corr = df.corr()
columns = np.full((corr.shape[0],), True, dtype=bool)
for i in range(corr.shape[0]):
    for j in range(i+1, corr.shape[0]):
        if corr.iloc[i,j] >= 0.9:
            if columns[j]:
                columns[j] = False
selected_columns = df.columns[columns]
data = df[selected_columns]

In [ ]:
data

         Attr1    Attr2    Attr3    Attr4  ...    Attr59   Attr60   Attr61  class
0     0.088238  0.55472  0.01134  1.02050  ...  0.002024   7.2711   4.7343    0.0
1    -0.006202  0.48465  0.23298  1.59980  ...  0.152220   6.0911   3.2749    0.0
2     0.130240  0.22142  0.57751  3.60820  ...  0.000000   8.7934   2.9870    0.0
3    -0.089951  0.88700  0.26927  1.52220  ...  2.878700   7.6524   3.3302    0.0
4     0.048179  0.55041  0.10765  1.24370  ...  0.139380  10.1180   4.0950    0.0
...        ...      ...      ...      ...  ...       ...      ...      ...    ...
7022  0.018371  0.47410 -0.13619  0.60839  ...  0.274140  73.5050  79.2370    1.0
7023 -0.013359  0.58354 -0.02265  0.92896  ...  0.805920  10.5990   7.1740    1.0
7024  0.006338  0.50276  0.43923  1.87360  ...  0.000000  10.4700   6.0759    1.0
7025 -0.041643  0.84810 -0.12852  0.57485  ...  3.593100  39.7030   3.1420    1.0
7026  0.014946  0.94648  0.03211  1.03630  ...  1.179200  15.0360   4.1741    1.0

[43405 rows x 36 columns]

## Intalling HyperOpt

In [ ]:
!pip install hyperopt

Requirement already satisfied: hyperopt in /usr/local/lib/python3.6/dist-packages (0.1.2)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from hyperopt) (1.15.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from hyperopt) (1.18.5)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from hyperopt) (0.16.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.6/dist-packages (from hyperopt) (2.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from hyperopt) (1.4.1)
Requirement already satisfied: pymongo in /usr/local/lib/python3.6/dist-packages (from hyperopt) (3.10.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from hyperopt) (4.41.1)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.6/dist-packages (from networkx->hyperopt) (4.4.2)

## HyperOpt codes

In [ ]:
import xgboost as xgb
import hyperopt

In [ ]:
from hyperopt import Trials, STATUS_OK, tpe, hp, fmin

In [ ]:
def objective(space):

    #warnings.filterwarnings(action='ignore', category=DeprecationWarning)
    classifier = xgb.XGBClassifier(base_score = 0.5 , n_estimators = space['n_estimators'],
                            max_depth = int(space['max_depth']),
                            learning_rate = space['learning_rate'],
                            #gamma = space['gamma'],
                            min_child_weight = space['min_child_weight'],
                            subsample = space['subsample'],
                            colsample_bytree = space['colsample_bytree']
                            )
    
    classifier.fit(data[selected_columns].drop(columns = ['class']), data['class'])

    # Applying k-Fold Cross Validation
    from sklearn.model_selection import cross_val_score
    accuracies = cross_val_score(estimator = classifier, X = data[selected_columns].drop(columns = ['class']), y = data['class'], cv = 5)
    CrossValMean = accuracies.mean()

    #print("CrossValMean:", CrossValMean)

    return{'loss':1-CrossValMean, 'status': STATUS_OK }

space = {
    'max_depth' : hp.choice('max_depth', range(3, 10, 1)),
    'learning_rate' : hp.quniform('learning_rate', 0.01, 0.5, 0.01),
    'n_estimators' : hp.choice('n_estimators', range(100, 205, 5)),
    'min_child_weight' : hp.quniform('min_child_weight', 1, 10, 1),
    'subsample' : hp.quniform('subsample', 0.1, 1, 0.01),
    'colsample_bytree' : hp.quniform('colsample_bytree', 0.1, 1.0, 0.01)}

trials = Trials()
best = fmin(fn=objective,
            space=space,
            algo=tpe.suggest,
            max_evals=50,
            trials=trials)

print("Best: ", best)

 76%|███████▌  | 38/50 [1:28:23<28:00, 140.03s/it, best loss: 0.036124870406635146]

In [ ]:
df.shape

(43405, 65)